[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/font",
    "crates/ghostty-vt",
    "crates/pty",
    "crates/renderer",
    "crates/terminal",
    "crates/ui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
log = "0.4.29"
async-channel = "2.5.0"
crossbeam-channel = "0.5.15"
bytemuck = { version = "1.25.0", features = ["derive"] }
rapidhash = "4.4.0"

windows = "0.61"
windows-core = "0.61"
windows-sys = { version = "0.59" }
windows-numerics = "0.2"

# Update the below paths to match your local vendored source
gpui = { git = "file:///D:/projects/rust/rustty/vendor/zed/" }
gpui_platform = { git = "file:///D:/projects/rust/rustty/vendor/zed/" }

[profile.release]
debug = true
strip = "none"
