[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/config",
    "crates/font",
    "crates/ghostty",
    "crates/harfbuzz",
    "crates/renderer",
    "crates/terminal",
    "crates/ui",
    "crates/utils",
    "crates/zconpty",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
doc_markdown = "allow"

str_to_string = "warn"
unused_trait_names = "warn"
precedence_bits = "warn"
cognitive_complexity = "warn"

# as_pointer_underscore = "warn"
# single_call_fn = "warn"
# redundant_type_annotations = "warn"

[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0.19"

log = "0.4.29"

async-channel = "2.5.0"
crossbeam-queue = "0.3.12"
crossbeam-channel = "0.5.15"

rustc-hash = "2.1.1"
parking_lot = "0.12.5"
better_mimalloc_rs = "0.1.1"

windows = "0.62"
windows-core = "0.62"
windows-numerics = "0.3"

gpui = { git = "https://github.com/arc-source-coder/zed/" }
gpui_platform = { git = "https://github.com/arc-source-coder/zed/" }

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
