[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/ghostty-vt",
    "crates/pty",
    "crates/renderer",
    "crates/terminal",
    "crates/ui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
async-channel = "2.5.0"
gpui = { git = "file:///D:/projects/rust/rustty/vendor/zed/" }
gpui_platform = { git = "file:///D:/projects/rust/rustty/vendor/zed/" }
