[package]
name = "terminal"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true

log.workspace = true

async-channel.workspace = true
crossbeam-queue.workspace = true
crossbeam-channel.workspace = true

config = { path = "../config" }
ghostty = { path = "../ghostty" }
zconpty = { path = "../zconpty" }

[lints]
workspace = true
