[package]
name = "terminal"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
async-channel.workspace = true
gpui.workspace = true
ghostty_vt = { path = "../ghostty-vt" }
pty = { path = "../pty" }
crossbeam-channel.workspace = true
crossbeam-queue.workspace = true
windows-sys = {
    workspace = true,
    features = [
        "Win32_Foundation",
        "Win32_System_Console",
    ]
}
bytes = "1.11.1"
