const std = @import("std");

const handle_mod = @import("handle.zig");
const TerminalHandle = handle_mod.TerminalHandle;

const key_encode = @import("ghostty/src/input/key_encode.zig");
const input_key = @import("ghostty/src/input/key.zig");

/// Encode a key event using the terminal's current mode state.
/// Returns the number of bytes written to buf (0 = no output for this event).
/// Returns 0 if handle is null or buf is null.
export fn ghostty_vt_terminal_encode_key(
    ptr: ?*anyopaque,
    /// Ghostty Key enum value (c_int)
    key_val: c_int,
    /// Modifier bitfield (Mods packed u16)
    mods: u16,
    /// Action: 0=release, 1=press, 2=repeat
    action: u8,
    /// UTF-8 text generated by the key event (for kitty protocol)
    text_ptr: ?[*]const u8,
    text_len: usize,
    /// Output buffer
    buf: ?[*]u8,
    buf_len: usize,
) callconv(.c) usize {
    if (ptr == null or buf == null) return 0;
    const handle: *TerminalHandle = @ptrCast(@alignCast(ptr.?));

    const opts = key_encode.Options.fromTerminal(&handle.terminal_inst);

    const event: input_key.KeyEvent = .{
        .key = @enumFromInt(key_val),
        .mods = @bitCast(mods),
        .action = @enumFromInt(action),
        .utf8 = if (text_ptr) |p| p[0..text_len] else "",
    };

    // Write into a fixed buffer writer backed by the caller's buffer.
    var writer: std.Io.Writer = .fixed(buf.?[0..buf_len]);
    key_encode.encode(&writer, event, opts) catch return 0;
    return writer.end;
}

/// Encode a mouse event using the terminal's current mouse format.
/// button: 0=left, 1=middle, 2=right, 3=release/none, 64=scroll_up, 65=scroll_down,
///         66-67=scroll_left/right, 128-129=back/forward
/// action: 0=press, 1=release, 2=motion
/// mods: shift=bit0, alt=bit1, ctrl=bit2 (simplified, not full Mods)
/// x, y: 0-indexed viewport cell coordinates
/// Returns bytes written to buf (0 = nothing to encode or error).
export fn ghostty_vt_terminal_encode_mouse(
    ptr: ?*anyopaque,
    button: u8,
    action: u8,
    mods: u8,
    x: u16,
    y: u16,
    buf: ?[*]u8,
    buf_len: usize,
) callconv(.c) usize {
    if (ptr == null or buf == null) return 0;
    const handle: *TerminalHandle = @ptrCast(@alignCast(ptr.?));

    const mouse_format = handle.terminal_inst.flags.mouse_format;
    const mouse_event = handle.terminal_inst.flags.mouse_event;

    // Build the button code
    var button_code: u8 = button;
    if (action == 1 and mouse_format != .sgr and mouse_format != .sgr_pixels) {
        // Release is always 3 in non-SGR formats
        button_code = 3;
    }

    // Add modifier bits (only if not x10 mode)
    if (mouse_event != .x10) {
        if (mods & 1 != 0) button_code += 4; // shift
        if (mods & 2 != 0) button_code += 8; // alt
        if (mods & 4 != 0) button_code += 16; // ctrl
    }

    // Motion flag
    if (action == 2) button_code += 32;

    var fbs = std.io.fixedBufferStream(buf.?[0..buf_len]);
    const writer = fbs.writer();

    switch (mouse_format) {
        .x10 => {
            if (x > 222 or y > 222) return 0;
            writer.writeAll("\x1b[M") catch return 0;
            writer.writeByte(32 + button_code) catch return 0;
            writer.writeByte(32 + @as(u8, @intCast(x)) + 1) catch return 0;
            writer.writeByte(32 + @as(u8, @intCast(y)) + 1) catch return 0;
        },
        .utf8 => {
            writer.writeAll("\x1b[M") catch return 0;
            writer.writeByte(32 + button_code) catch return 0;
            var tmp: [4]u8 = undefined;
            var n = std.unicode.utf8Encode(@intCast(32 + x + 1), &tmp) catch return 0;
            writer.writeAll(tmp[0..n]) catch return 0;
            n = std.unicode.utf8Encode(@intCast(32 + y + 1), &tmp) catch return 0;
            writer.writeAll(tmp[0..n]) catch return 0;
        },
        .sgr => {
            const final: u8 = if (action == 1) 'm' else 'M';
            std.fmt.format(writer.any(), "\x1b[<{d};{d};{d}{c}", .{
                button_code,
                @as(u32, x) + 1,
                @as(u32, y) + 1,
                final,
            }) catch return 0;
        },
        .urxvt => {
            std.fmt.format(writer.any(), "\x1b[{d};{d};{d}M", .{
                @as(u16, 32) + button_code,
                @as(u32, x) + 1,
                @as(u32, y) + 1,
            }) catch return 0;
        },
        .sgr_pixels => {
            // For pixel mode, x/y are passed as cell coords.
            // The caller (Rust terminal crate) should convert to pixels
            // before calling if pixel mode is active.
            const final: u8 = if (action == 1) 'm' else 'M';
            std.fmt.format(writer.any(), "\x1b[<{d};{d};{d}{c}", .{
                button_code,
                @as(u32, x) + 1,
                @as(u32, y) + 1,
                final,
            }) catch return 0;
        },
    }

    return fbs.pos;
}
