[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
terminal = { path = "../terminal" }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Wdk_System_SystemServices", "Win32_System_SystemInformation", "UI_ViewManagement"] }
