[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true

better_mimalloc_rs.workspace = true

ui = { path = "../ui" }
renderer = { path = "../renderer" }
terminal = { path = "../terminal" }
config = { version = "0.1.0", path = "../config" }

[lints]
workspace = true
