[package]
name = "font"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
rustc-hash.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
unicode-properties = "0.1.4"

utils = { path = "../utils" }
config = { path = "../config" }
ghostty = { path = "../ghostty" }
harfbuzz = { path = "../harfbuzz" }
log.workspace = true


[target.'cfg(target_os = "windows")'.dependencies]
windows-core.workspace = true
windows-numerics.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_DirectWrite",
    "Win32_Globalization",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
] }

[lints]
workspace = true
